### ISSUE TITLE
Specflow Scenario Outline

### ISSUE THREAD

**Issue by Mormam** [MajorNibbles/AzureDevOpsTestConnectorPublic#3] opened 2019-12-05 14:04 UTC
It does not copy the steps to test devops when the scenario uses **Examples:**

**Comment by MajorNibbles** [comment] 2020-01-19 19:35
Unfortunately I'm unable to replicate this, can you please supply the SpecFlow feature file that produced this issue?

**Comment by Mormam** [comment] 2020-01-21 17:49
@web @Term @Regression
#TestCaseId(147)
Scenario Outline: Contact fill an enquiry for travel portal services 
	Given I have access to the contact in village <village>
	And I fill a general enquiry
	When i send Enquiry
	Then no field error is displayed

	Examples:
	| village |
	| fv        | 

========DevOps=================
![image](https://user-images.githubusercontent.com/6449018/72829238-4df60e00-3c76-11ea-9861-9fd5f017dd08.png)

**Comment by MajorNibbles** [comment] 2020-01-21 18:35
Thanks, I'm still unable to reproduce this issue, would you be able to send me the whole file? I wonder if other tests might be interrupting the parsing.

**Comment by aurnoi1** [comment] 2020-01-21 18:54
I also have the problem.

Environment:
Azure DevOps Test Connector build 1.3.2.
VS2019 Version 16.4.3
Deveroom 1.5.1 as Gherkin syntax highlighter.

Both scenarios are created as TestCase but only the scenario 3012 get steps. The scenario outline test case is empty.

I have attached the file.

[View a main menu.feature.txt](https://github.com/MajorNibbles/AzureDevOpsTestConnectorPublic/files/4093051/View.a.main.menu.feature.txt)

**Comment by MajorNibbles** [comment] 2020-01-21 19:17
Thanks Aurnoi1, I've found the issue you was experiencing was due to the < > characters stopping ADO from accepting the JSON package. I found out these have to be handled using &amp;lt; and &amp;gt; respectively. I have just released version 1.3.3 (due to be released in next 10 minutes) which should fix this for you.

Mormam, can you please see if this may fix your issue too?

**Comment by aurnoi1** [comment] 2020-01-21 19:43
I confirm that it fix my issue. The notation <placeholder> is the one used in  Gherkin [(See Scenario Outline)](https://specflow.org/documentation/Using-Gherkin-Language-in-SpecFlow) to refer the column in Examples table. 

I see that the test case does not include this values. I will think about a way to correctly display them in Azure and open another issue.

Thanks for the fix!

**Comment by Mormam** [comment] 2020-01-21 23:33
I confirm it resolve the issue of update/create Scenarios Outline.

**Closed** 2020-01-22 14:35 UTC
